name: moml-ca
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.3
  - pytorch-cuda=12.1
  - numpy>=1.26,<2.0
  - pandas>=2.2,<3.0
  - scipy>=1.11,<2.0
  - rdkit>=2024.03
  - pip:
      - torch-geometric>=2.5,<2.6
      - simpy>=4.1.1,<5.0
      - mkdocs>=1.5,<2.0
      - mkdocs-material>=9.5,<10.0
      - mkdocstrings-python>=1.8,<2.0
      - pytest>=8.2,<9.0
      - pytest-cov>=5.0,<6.0
      - ruff>=0.6.8,<0.8
      - mypy>=1.10,<2.0
      - pre-commit>=3.7,<4.0
      - packaging>=24.0,<25.0
