site_name: MoML Documentation
repo_url: https://github.com/example/moml
nav:
  - Getting Started: docs/getting-started.md
  - How Predictions Become MD: docs/how-predictions-become-md.md
theme:
  name: material
