# Base configuration shared across experiments.
---
defaults:
  - data: default
  - model: baseline_gnn
  - pipeline: experiment
  - simulation: null

project:
  name: moml-ca
  version: 0.1.0
  seed: 1337

paths:
  data_dir: ${oc.env:DATA_DIR,data/}
  artifacts_dir: ${oc.env:ARTIFACTS_DIR,artifacts/}
  logs_dir: ${oc.env:LOGS_DIR,logs/}

trainer:
  accelerator: gpu
  devices: 1
  precision: 32
  max_epochs: 100

logging:
  level: INFO
  format: "%(asctime)s | %(name)s | %(levelname)s | %(message)s"
  capture_warnings: true

registry:
  feature_store: null
  experiment_tracker: null
