name: moml
channels:
  - pytorch
  - pyg
  - conda-forge
dependencies:
  - python=3.11
  - pytorch>=2.2,<2.4
  - torchvision>=0.17
  - torchaudio>=2.2
  - cpuonly
  - pyg>=2.4
  - rdkit
  - openmm>=8.0
  - openff-toolkit>=0.15
  - numpy
  - pandas
  - scikit-learn
  - dvc>=3,<4
  - hydra-core>=1.3
  - typer>=0.9
  - wandb>=0.16
  - pip
  - pip:
      - mdtraj>=1.9.9
      - mdanalysis>=2.6
